[extend]
useDefault = true

[[paths]]
regex = '''docs/.*\.md'''
ignore = true

[[rules]]
id = "custom-api-key"
description = "Mailgun API Key"
regex = '''key-[a-f0-9]{32}'''

[[rules]]
id = "allow-email"
description = "Email address in docs"
regex = '''\S+@\S+\.\S+'''

[rules.allowlist]
description = "Allow emails in docs folder"
paths = ['''^docs/.*\.md$''']
